Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# An example input vector
x = np.array(
    [ 0.4967, -0.1383,  0.6477,  1.523 , -0.2342, -0.2341,  1.5792,
      0.7674, -0.4695,  0.5426, -0.4634, -0.4657,  0.242 , -1.9133,
      -1.7249, -0.5623, -1.0128,  0.3142, -0.908 , -1.4123,  1.4656,
      -0.2258,  0.0675, -1.4247, -0.5444,  0.1109, -1.151 ,  0.3757,
      -0.6006, -0.2917, -0.6017,  1.8523])
N = len(x)

plt.plot(x)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m [38;5;66;03m# An example input vector[39;00m
[0;32m----> 2[0m x [38;5;241m=[39m [43mnp[49m[38;5;241m.[39marray(
[1;32m      3[0m     [ [38;5;241m0.4967[39m, [38;5;241m-[39m[38;5;241m0.1383[39m,  [38;5;241m0.6477[39m,  [38;5;241m1.523[39m , [38;5;241m-[39m[38;5;241m0.2342[39m, [38;5;241m-[39m[38;5;241m0.2341[39m,  [38;5;241m1.5792[39m,
[1;32m      4[0m       [38;5;241m0.7674[39m, [38;5;241m-[39m[38;5;241m0.4695[39m,  [38;5;241m0.5426[39m, [38;5;241m-[39m[38;5;241m0.4634[39m, [38;5;241m-[39m[38;5;241m0.4657[39m,  [38;5;241m0.242[39m , [38;5;241m-[39m[38;5;241m1.9133[39m,
[1;32m      5[0m       [38;5;241m-[39m[38;5;241m1.7249[39m, [38;5;241m-[39m[38;5;241m0.5623[39m, [38;5;241m-[39m[38;5;241m1.0128[39m,  [38;5;241m0.3142[39m, [38;5;241m-[39m[38;5;241m0.908[39m , [38;5;241m-[39m[38;5;241m1.4123[39m,  [38;5;241m1.4656[39m,
[1;32m      6[0m       [38;5;241m-[39m[38;5;241m0.2258[39m,  [38;5;241m0.0675[39m, [38;5;241m-[39m[38;5;241m1.4247[39m, [38;5;241m-[39m[38;5;241m0.5444[39m,  [38;5;241m0.1109[39m, [38;5;241m-[39m[38;5;241m1.151[39m ,  [38;5;241m0.3757[39m,
[1;32m      7[0m       [38;5;241m-[39m[38;5;241m0.6006[39m, [38;5;241m-[39m[38;5;241m0.2917[39m, [38;5;241m-[39m[38;5;241m0.6017[39m,  [38;5;241m1.8523[39m])
[1;32m      8[0m N [38;5;241m=[39m [38;5;28mlen[39m(x)
[1;32m     10[0m plt[38;5;241m.[39mplot(x)

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

